/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Custom colors from HTML design
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#3d4944",
        "error": "#ba1a1a",
        "on-background": "#0a1842",
        "outline-variant": "#bccac2",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#410001",
        "secondary-fixed-dim": "#ffb4aa",
        "on-secondary-fixed-variant": "#8c1714",
        "tertiary-container": "#976d00",
        "on-error-container": "#93000a",
        "surface-dim": "#d0d8ff",
        "on-surface": "#0a1842",
        "surface-variant": "#dce1ff",
        "surface-container": "#ebedff",
        "inverse-surface": "#212e58",
        "tertiary-fixed-dim": "#f4be4e",
        "inverse-primary": "#6adab6",
        "on-primary-fixed-variant": "#00513e",
        "on-primary-fixed": "#002117",
        "tertiary": "#785600",
        "on-tertiary-fixed": "#261900",
        "on-error": "#ffffff",
        "surface-container-low": "#f3f2ff",
        "secondary-fixed": "#ffdad5",
        "on-primary-container": "#f5fff8",
        "inverse-on-surface": "#eff0ff",
        "secondary-container": "#fc695b",
        "primary-container": "#008467",
        "on-tertiary-fixed-variant": "#5d4200",
        "secondary": "#ae3028",
        "primary-fixed-dim": "#6adab6",
        "on-tertiary-container": "#fffbff",
        "primary-fixed": "#87f7d1",
        "on-secondary-container": "#690004",
        "on-primary": "#ffffff",
        "surface-bright": "#faf8ff",
        "surface-tint": "#006c53",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        "label-md": ["Inter"],
        "headline-xl": ["Quicksand"],
        "body-lg": ["Inter"],
        "headline-lg": ["Quicksand"],
        "label-sm": ["Inter"],
        "headline-md": ["Quicksand"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      spacing: {
        "lg": "48px",
        "sm": "12px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        "base": "8px",
        "xl": "80px",
        "gutter": "24px",
        "md": "24px",
        "xs": "4px",
      },
    },
  },
  plugins: [],
}
