/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["AuthController_signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email and password */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out and revoke current session */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all classes */
        get: operations["ClassesController_findAll"];
        put?: never;
        /** Create a class (admin only, specify teacherId) */
        post: operations["ClassesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available classes for self-enrollment */
        get: operations["ClassesController_findAvailable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get class by ID */
        get: operations["ClassesController_findOne"];
        put?: never;
        post?: never;
        /** Delete a class */
        delete: operations["ClassesController_remove"];
        options?: never;
        head?: never;
        /** Update a class */
        patch: operations["ClassesController_update"];
        trace?: never;
    };
    "/classes/{id}/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enroll a student */
        post: operations["ClassesController_addEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes/{id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Student self-join class */
        post: operations["ClassesController_join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes/{id}/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pending enrollment requests */
        get: operations["ClassesController_getRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes/{classId}/enrollments/{studentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a student enrollment */
        delete: operations["ClassesController_removeEnrollment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List assignments, optionally filtered by class */
        get: operations["AssignmentsController_findAll"];
        put?: never;
        /** Create an assignment */
        post: operations["AssignmentsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get assignment by ID */
        get: operations["AssignmentsController_findOne"];
        put?: never;
        post?: never;
        /** Delete an assignment */
        delete: operations["AssignmentsController_remove"];
        options?: never;
        head?: never;
        /** Update an assignment */
        patch: operations["AssignmentsController_update"];
        trace?: never;
    };
    "/rubrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rubrics, optionally filtered by assignment */
        get: operations["RubricsController_findAll"];
        put?: never;
        /** Create a rubric with criteria */
        post: operations["RubricsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rubrics/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get rubric with criteria */
        get: operations["RubricsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rubrics/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Confirm a rubric (enables grading against it) */
        patch: operations["RubricsController_confirm"];
        trace?: never;
    };
    "/rubrics/import-pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a PDF rubric and extract criteria */
        post: operations["RubricsController_importPdf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rubrics/from-pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a PDF rubric and create the rubric in one call */
        post: operations["RubricsController_fromPdf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List submissions, optionally filtered by status and assignment */
        get: operations["SubmissionsController_findAll"];
        put?: never;
        /** Submit an assignment (student) */
        post: operations["SubmissionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/import-pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a submission as PDF */
        post: operations["SubmissionsController_importPdf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get submission with scores */
        get: operations["SubmissionsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grades/submissions/{submissionId}/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grade a submission (triggers AI grading agent) */
        post: operations["GradingController_grade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grades/submissions/{submissionId}/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all scores with criteria for a submission */
        get: operations["GradingController_getScores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grades/scores/{scoreId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update points awarded and notes for a single score */
        patch: operations["GradingController_updateScore"];
        trace?: never;
    };
    "/grades/confirm-all/{submissionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Confirm all grades in a submission */
        patch: operations["GradingController_confirmAll"];
        trace?: never;
    };
    "/grades/backfill-feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-run feedback writer for all confirmed submissions missing AI feedback */
        post: operations["GradingController_backfillFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List notifications for current user */
        get: operations["NotificationsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark notification as read */
        patch: operations["NotificationsController_markRead"];
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reports, optionally filtered by student */
        get: operations["ReportsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single report by ID */
        get: operations["ReportsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List alerts for teacher's classes */
        get: operations["AlertsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{id}/teacher-detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get structured analysis data for an alert */
        get: operations["AlertsController_getTeacherDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Resolve or dismiss an alert */
        patch: operations["AlertsController_resolve"];
        trace?: never;
    };
    "/assistant/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a message to the AI assistant */
        post: operations["AssistantController_chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a material file (PDF or text) */
        post: operations["MaterialsController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials/class/{classId}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search material chunks by semantic similarity */
        get: operations["MaterialsController_searchChunks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials/class/{classId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List materials for a class */
        get: operations["MaterialsController_findByClass"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a material with its chunks */
        get: operations["MaterialsController_findOne"];
        put?: never;
        post?: never;
        /** Delete a material */
        delete: operations["MaterialsController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{id}/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get confirmed grades for a student */
        get: operations["StudentsController_getGrades"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{id}/grades/{submissionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get confirmed grades for a specific submission */
        get: operations["StudentsController_getSubmissionGrades"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{id}/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get enrolled classes for a student */
        get: operations["StudentsController_getClasses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update student details */
        patch: operations["StudentsController_update"];
        trace?: never;
    };
    "/students/{id}/guardian": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link a guardian to a student */
        post: operations["StudentsController_linkGuardian"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import attendance records in batch */
        post: operations["AttendanceController_importBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{id}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get attendance records for a student */
        get: operations["AttendanceController_getByStudent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes/{id}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get attendance records for a class */
        get: operations["AttendanceController_getByClass"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Role-aware dashboard overview */
        get: operations["DashboardController_getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Role-aware dashboard insights */
        get: operations["DashboardController_getInsights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/insights/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-student insights drill-down */
        get: operations["DashboardController_getStudentInsights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all grades */
        get: operations["GradesController_findAll"];
        put?: never;
        /** Create a grade */
        post: operations["GradesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grades/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get grade by ID with classes */
        get: operations["GradesController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grades/{id}/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List classes in a grade */
        get: operations["GradesController_getClasses"];
        put?: never;
        /** Add a class to a grade */
        post: operations["GradesController_addClass"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grades/{gradeId}/classes/{classId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a class from a grade */
        delete: operations["GradesController_removeClass"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrollments/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Approve a pending enrollment request */
        patch: operations["EnrollmentsController_approve"];
        trace?: never;
    };
    "/enrollments/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reject a pending enrollment request */
        patch: operations["EnrollmentsController_reject"];
        trace?: never;
    };
    "/teachers/{id}/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List grades assigned to a teacher */
        get: operations["TeachersController_getGrades"];
        put?: never;
        /** Assign a grade to a teacher */
        post: operations["TeachersController_addGrade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teachers/{teacherId}/grades/{gradeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a grade from a teacher */
        delete: operations["TeachersController_removeGrade"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List/search users (ADMIN only) */
        get: operations["UsersController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/homework-help": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask the homework helper agent for help */
        post: operations["HomeworkHelperController_help"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/homework-help/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get past homework help interactions */
        get: operations["HomeworkHelperController_getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/homework-help/{interactionId}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Submit feedback on a homework help interaction */
        patch: operations["HomeworkHelperController_submitFeedback"];
        trace?: never;
    };
    "/quizzes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List quizzes (role-aware: teacher-owned or student enrolled), optionally filtered by class */
        get: operations["QuizzesController_findAll"];
        put?: never;
        /** Create a quiz with nested questions */
        post: operations["QuizzesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quizzes/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a quiz with AI */
        post: operations["QuizzesController_generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quizzes/attempts/{attemptId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an attempt with answers, quiz, student and violations */
        get: operations["QuizzesController_getAttempt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quizzes/attempts/{attemptId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Confirm all answers of an attempt (rejects if any answer is ungraded) */
        patch: operations["QuizzesController_confirmAttempt"];
        trace?: never;
    };
    "/quizzes/attempts/{attemptId}/violations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report a quiz violation (own attempt only) */
        post: operations["QuizzesController_reportViolation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quizzes/answers/{answerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update points awarded for a single answer */
        patch: operations["QuizzesController_updateAnswer"];
        trace?: never;
    };
    "/quizzes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a quiz with questions */
        get: operations["QuizzesController_findOne"];
        put?: never;
        post?: never;
        /** Delete a quiz (cascades questions and attempts) */
        delete: operations["QuizzesController_remove"];
        options?: never;
        head?: never;
        /** Update a quiz (replaces/upserts questions when included) */
        patch: operations["QuizzesController_update"];
        trace?: never;
    };
    "/quizzes/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Publish a quiz */
        patch: operations["QuizzesController_publish"];
        trace?: never;
    };
    "/quizzes/{quizId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start (or resume) a quiz attempt */
        post: operations["QuizzesController_startAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quizzes/{quizId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit answers for a quiz attempt */
        post: operations["QuizzesController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quizzes/{quizId}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all attempts for a quiz */
        get: operations["QuizzesController_getQuizAttempts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SignupDto: {
            /** Format: email */
            email: string;
            password: string;
            name: string;
            /** @enum {string} */
            role: "TEACHER" | "STUDENT" | "GUARDIAN" | "ADMIN";
            gradeLevel?: number;
        };
        AuthResponseDto: {
            /** Format: uuid */
            id: string;
            email: string;
            name: string;
            /** @enum {string} */
            role: "TEACHER" | "STUDENT" | "GUARDIAN" | "ADMIN";
        };
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        UserDto: {
            /** Format: uuid */
            id: string;
            email: string;
            name: string;
            /** @enum {string} */
            role: "TEACHER" | "STUDENT" | "GUARDIAN" | "ADMIN";
        };
        CreateClassDto: {
            name: string;
            description?: string;
            /** Format: uuid */
            teacherId: string;
        };
        ClassDto: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string | null;
            /** Format: uuid */
            teacherId: string;
            createdAt: string;
            updatedAt: string;
        };
        UpdateClassDto: {
            name?: string;
            description?: string;
        };
        AddEnrollmentDto: {
            /** Format: uuid */
            studentId: string;
        };
        CreateAssignmentDto: {
            title: string;
            description?: string;
            /** Format: date-time */
            dueDate: string;
            totalPoints: number;
            /** Format: uuid */
            classId: string;
        };
        AssignmentDto: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string | null;
            dueDate: string;
            totalPoints: number;
            /** Format: uuid */
            classId: string;
            createdAt: string;
            updatedAt: string;
        };
        UpdateAssignmentDto: {
            title?: string;
            description?: string;
            /** Format: date-time */
            dueDate?: string;
            totalPoints?: number;
        };
        CreateRubricDto: {
            title: string;
            /** Format: uuid */
            assignmentId: string;
            criteria: {
                description: string;
                maxPoints: number;
            }[];
        };
        CreateSubmissionDto: {
            /** Format: uuid */
            assignmentId: string;
            content: string;
        };
        SubmissionDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            assignmentId: string;
            /** Format: uuid */
            studentId: string;
            /** @enum {string} */
            status: "SUBMITTED" | "GRADING_IN_PROGRESS" | "REVIEW_READY" | "CONFIRMED";
            createdAt: string;
            updatedAt: string;
        };
        NotificationDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            type: string;
            /** @enum {string} */
            channel: "EMAIL" | "PUSH";
            title: string;
            body: string | null;
            /** Format: date-time */
            readAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ReportDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            studentId: string;
            /** Format: uuid */
            alertId: string;
            parentSection: string;
            teacherSection: string;
            managementSection: string;
            createdAt: string;
        };
        AlertDto: {
            /** Format: uuid */
            id: string;
            type: string;
            reason: string;
            status: string;
            /** Format: uuid */
            studentId: string;
            createdAt: string;
            studentName: string;
            className: string | null;
            severity: string | null;
            skillGapCount: number;
        };
        ResolveAlertDto: {
            /** @enum {string} */
            status: "RESOLVED" | "DISMISSED";
        };
        ChatDto: {
            /** Format: uuid */
            classId: string;
            messages: {
                /** @enum {string} */
                role: "user" | "assistant";
                content: string;
            }[];
            newMessage: string;
        };
        ChatResponseDto: {
            reply: string;
            quiz?: {
                title: string;
                questions: {
                    /** @enum {string} */
                    type: "mcq" | "short_answer";
                    question: string;
                    options?: string[];
                    correctAnswer: string;
                    explanation?: string;
                }[];
            };
        };
        GradeDto: {
            /** Format: uuid */
            id: string;
            level: number;
            name: string;
            createdAt: string;
        };
        UpdateStudentDto: {
            name?: string;
            /** Format: email */
            email?: string;
            /** Format: uuid */
            gradeId?: string;
            /** Format: uuid */
            guardianId?: string;
        };
        ImportAttendanceDto: {
            records: {
                /** Format: uuid */
                studentId: string;
                /** Format: uuid */
                classId: string;
                date: string;
                /** @enum {string} */
                status: "PRESENT" | "ABSENT" | "LATE" | "EXCUSED";
            }[];
        };
        AttendanceResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            studentId: string;
            /** Format: uuid */
            classId: string;
            date: string;
            /** @enum {string} */
            status: "PRESENT" | "ABSENT" | "LATE" | "EXCUSED";
            createdAt: string;
            updatedAt: string;
        };
        InsightsResponseDto: {
            /** @enum {string} */
            interval: "week" | "month";
            sections: {
                key: string;
                title: string;
                /** @enum {string} */
                chartType: "line" | "area" | "bar" | "radar" | "donut";
                series: {
                    label: string;
                    value: number;
                }[];
                delta?: {
                    deltaPercent: number;
                    /** @enum {string} */
                    direction: "up" | "down" | "flat";
                };
            }[];
            agentInsights: {
                id: string;
                type: string;
                title: string;
                body: string;
                studentName?: string;
                studentId?: string;
                childName?: string;
                childId?: string;
            }[];
            unreadNotifications: number;
        };
        GradeClassDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            gradeId: string;
            /** Format: uuid */
            classId: string;
        };
        CreateGradeDto: {
            level: number;
            name: string;
        };
        AddGradeClassDto: {
            /** Format: uuid */
            classId: string;
        };
        AddTeacherGradeDto: {
            /** Format: uuid */
            gradeId: string;
        };
        HomeworkHelpRequestDto: {
            /** Format: uuid */
            classId: string;
            question: string;
            /** Format: uuid */
            assignmentId?: string;
        };
        HomeworkHelpResponseDto: {
            answer: string;
            reply: string;
            /** @enum {string} */
            action: "HINT" | "EXPLANATION" | "REDIRECT_TEACHER";
            sources: string[];
            /** Format: uuid */
            interactionId: string;
            teacherNotified: boolean;
        };
        HomeworkHelpHistoryResponseDto: {
            interactions: {
                /** Format: uuid */
                id: string;
                question: string;
                answer: string;
                /** @enum {string} */
                action: "HINT" | "EXPLANATION" | "REDIRECT_TEACHER";
                sources: string[];
                feedback: string | null;
                createdAt: string;
            }[];
        };
        HomeworkHelpFeedbackDto: {
            /** @enum {string} */
            feedback: "HELPFUL" | "NOT_HELPFUL";
        };
        QuizWithAttemptStatusDto: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string | null;
            /** Format: uuid */
            classId: string;
            timeLimit: number | null;
            passingScore: number | null;
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "CLOSED";
            endsAt: string | null;
            createdAt: string;
            questions?: {
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                type: "MCQ" | "TRUE_FALSE" | "SHORT_ANSWER" | "ESSAY";
                question: string;
                options?: {
                    /** Format: uuid */
                    id: string;
                    text: string;
                    isCorrect?: boolean;
                }[];
                points: number;
                order: number;
            }[];
            /** @enum {string} */
            attemptStatus?: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED";
            /** Format: uuid */
            attemptId?: string | null;
        };
        GenerateQuizDto: {
            /** Format: uuid */
            classId: string;
            topic: string;
            questionCount: number;
            types: ("MCQ" | "TRUE_FALSE" | "SHORT_ANSWER" | "ESSAY")[];
        };
        GenerateQuizResultDto: {
            /** Format: uuid */
            quizId: string;
            title: string;
            message: string;
        };
        QuizAttemptDetailDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            quizId: string;
            /** Format: uuid */
            studentId: string;
            startedAt: string;
            submittedAt: string | null;
            totalScore: number | null;
            /** @enum {string} */
            status: "IN_PROGRESS" | "COMPLETED";
            violations?: {
                /** Format: uuid */
                id: string;
                type: string;
                createdAt: string;
            }[];
            expiresAt: string | null;
            serverNow?: string;
            student?: {
                /** Format: uuid */
                id: string;
                name: string;
            };
            quiz?: {
                /** Format: uuid */
                id: string;
                title: string;
                description: string | null;
                /** Format: uuid */
                classId: string;
                timeLimit: number | null;
                passingScore: number | null;
                /** @enum {string} */
                status: "DRAFT" | "PUBLISHED" | "CLOSED";
                endsAt: string | null;
                createdAt: string;
                questions?: {
                    /** Format: uuid */
                    id: string;
                    /** @enum {string} */
                    type: "MCQ" | "TRUE_FALSE" | "SHORT_ANSWER" | "ESSAY";
                    question: string;
                    options?: {
                        /** Format: uuid */
                        id: string;
                        text: string;
                        isCorrect?: boolean;
                    }[];
                    points: number;
                    order: number;
                }[];
            };
            answers?: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                questionId: string;
                answer: string;
                pointsAwarded: number | null;
                aiFeedback: string | null;
                isConfirmed: boolean;
            }[];
        };
        ReportViolationDto: {
            /** @enum {string} */
            type: "TAB_SWITCH" | "FULLSCREEN_EXIT";
        };
        QuizViolationDto: {
            /** Format: uuid */
            id: string;
            type: string;
            createdAt: string;
        };
        UpdateAnswerDto: {
            pointsAwarded: number;
        };
        QuizAnswerDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            questionId: string;
            answer: string;
            pointsAwarded: number | null;
            aiFeedback: string | null;
            isConfirmed: boolean;
        };
        CreateQuizDto: {
            title: string;
            description?: string;
            /** Format: uuid */
            classId: string;
            timeLimit?: number;
            passingScore?: number;
            /** Format: date-time */
            endsAt?: string;
            questions: {
                /** Format: uuid */
                id?: string;
                /** @enum {string} */
                type: "MCQ" | "TRUE_FALSE" | "SHORT_ANSWER" | "ESSAY";
                question: string;
                options?: {
                    /** Format: uuid */
                    id?: string;
                    text: string;
                    isCorrect: boolean;
                }[];
                points?: number;
                order: number;
            }[];
        };
        QuizDto: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string | null;
            /** Format: uuid */
            classId: string;
            timeLimit: number | null;
            passingScore: number | null;
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "CLOSED";
            endsAt: string | null;
            createdAt: string;
            questions?: {
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                type: "MCQ" | "TRUE_FALSE" | "SHORT_ANSWER" | "ESSAY";
                question: string;
                options?: {
                    /** Format: uuid */
                    id: string;
                    text: string;
                    isCorrect?: boolean;
                }[];
                points: number;
                order: number;
            }[];
        };
        UpdateQuizDto: {
            title?: string;
            description?: string;
            /** Format: uuid */
            classId?: string;
            timeLimit?: number;
            passingScore?: number;
            /** Format: date-time */
            endsAt?: string;
            questions?: {
                /** Format: uuid */
                id?: string;
                /** @enum {string} */
                type: "MCQ" | "TRUE_FALSE" | "SHORT_ANSWER" | "ESSAY";
                question: string;
                options?: {
                    /** Format: uuid */
                    id?: string;
                    text: string;
                    isCorrect: boolean;
                }[];
                points?: number;
                order: number;
            }[];
            /** @enum {string} */
            status?: "DRAFT" | "PUBLISHED" | "CLOSED";
        };
        QuizAttemptDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            quizId: string;
            /** Format: uuid */
            studentId: string;
            startedAt: string;
            submittedAt: string | null;
            totalScore: number | null;
            /** @enum {string} */
            status: "IN_PROGRESS" | "COMPLETED";
            violations?: {
                /** Format: uuid */
                id: string;
                type: string;
                createdAt: string;
            }[];
            expiresAt: string | null;
            serverNow?: string;
        };
        SubmitQuizDto: {
            answers: {
                /** Format: uuid */
                questionId: string;
                answer: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClassesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassDto"][];
                };
            };
        };
    };
    ClassesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClassDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassDto"];
                };
            };
        };
    };
    ClassesController_findAvailable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClassesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassDto"];
                };
            };
        };
    };
    ClassesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClassesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClassDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassDto"];
                };
            };
        };
    };
    ClassesController_addEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddEnrollmentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClassesController_join: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClassesController_getRequests: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClassesController_removeEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                classId: string;
                studentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssignmentsController_findAll: {
        parameters: {
            query?: {
                classId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentDto"][];
                };
            };
        };
    };
    AssignmentsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssignmentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentDto"];
                };
            };
        };
    };
    AssignmentsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentDto"];
                };
            };
        };
    };
    AssignmentsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssignmentsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAssignmentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentDto"];
                };
            };
        };
    };
    RubricsController_findAll: {
        parameters: {
            query: {
                assignmentId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RubricsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRubricDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RubricsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RubricsController_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RubricsController_importPdf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RubricsController_fromPdf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                    /** Format: uuid */
                    assignmentId?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SubmissionsController_findAll: {
        parameters: {
            query?: {
                status?: string;
                assignmentId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDto"][];
                };
            };
        };
    };
    SubmissionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubmissionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDto"];
                };
            };
        };
    };
    SubmissionsController_importPdf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** Format: uuid */
                    assignmentId: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SubmissionsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GradingController_grade: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GradingController_getScores: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GradingController_updateScore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scoreId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GradingController_confirmAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GradingController_backfillFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_findAll: {
        parameters: {
            query?: {
                userId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationDto"][];
                };
            };
        };
    };
    NotificationsController_markRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportsController_findAll: {
        parameters: {
            query?: {
                studentId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDto"][];
                };
            };
        };
    };
    ReportsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDto"];
                };
            };
        };
    };
    AlertsController_findAll: {
        parameters: {
            query?: {
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertDto"][];
                };
            };
        };
    };
    AlertsController_getTeacherDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AlertsController_resolve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveAlertDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertDto"];
                };
            };
        };
    };
    AssistantController_chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponseDto"];
                };
            };
        };
    };
    MaterialsController_upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                    title?: string;
                    /** Format: uuid */
                    classId?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MaterialsController_searchChunks: {
        parameters: {
            query: {
                q: string;
                topK: string;
            };
            header?: never;
            path: {
                classId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MaterialsController_findByClass: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                classId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MaterialsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MaterialsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudentsController_getGrades: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeDto"][];
                };
            };
        };
    };
    StudentsController_getSubmissionGrades: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                submissionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeDto"][];
                };
            };
        };
    };
    StudentsController_getClasses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudentsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStudentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StudentsController_linkGuardian: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    guardianId?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AttendanceController_importBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportAttendanceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceResponseDto"][];
                };
            };
        };
    };
    AttendanceController_getByStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceResponseDto"][];
                };
            };
        };
    };
    AttendanceController_getByClass: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceResponseDto"][];
                };
            };
        };
    };
    DashboardController_getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role-aware dashboard data — shape varies by role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_getInsights: {
        parameters: {
            query?: {
                /** @description Bucket interval — defaults to week */
                interval?: "week" | "month";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Insights response envelope (sections + agent insights) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsResponseDto"];
                };
            };
        };
    };
    DashboardController_getStudentInsights: {
        parameters: {
            query?: {
                /** @description Bucket interval — defaults to week */
                interval?: "week" | "month";
            };
            header?: never;
            path: {
                /** @description Student user id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Insights response envelope scoped to one student */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsResponseDto"];
                };
            };
            /** @description No access to this student */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GradesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeDto"][];
                };
            };
        };
    };
    GradesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGradeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeDto"];
                };
            };
        };
    };
    GradesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeDto"];
                };
            };
        };
    };
    GradesController_getClasses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeClassDto"][];
                };
            };
        };
    };
    GradesController_addClass: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddGradeClassDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeClassDto"];
                };
            };
        };
    };
    GradesController_removeClass: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gradeId: string;
                classId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EnrollmentsController_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EnrollmentsController_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TeachersController_getGrades: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of grades */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TeachersController_addGrade: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTeacherGradeDto"];
            };
        };
        responses: {
            /** @description Grade assigned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TeachersController_removeGrade: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teacherId: string;
                gradeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grade removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findAll: {
        parameters: {
            query?: {
                role?: "TEACHER" | "STUDENT" | "GUARDIAN" | "ADMIN";
                /** @description Free-text name search */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HomeworkHelperController_help: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HomeworkHelpRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeworkHelpResponseDto"];
                };
            };
        };
    };
    HomeworkHelperController_getHistory: {
        parameters: {
            query?: {
                classId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeworkHelpHistoryResponseDto"];
                };
            };
        };
    };
    HomeworkHelperController_submitFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interactionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HomeworkHelpFeedbackDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    QuizzesController_findAll: {
        parameters: {
            query?: {
                classId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizWithAttemptStatusDto"][];
                };
            };
        };
    };
    QuizzesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuizDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizDto"];
                };
            };
        };
    };
    QuizzesController_generate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateQuizDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateQuizResultDto"];
                };
            };
        };
    };
    QuizzesController_getAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizAttemptDetailDto"];
                };
            };
        };
    };
    QuizzesController_confirmAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizAttemptDetailDto"];
                };
            };
        };
    };
    QuizzesController_reportViolation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportViolationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizViolationDto"];
                };
            };
        };
    };
    QuizzesController_updateAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                answerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAnswerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizAnswerDto"];
                };
            };
        };
    };
    QuizzesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizDto"];
                };
            };
        };
    };
    QuizzesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    QuizzesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuizDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizDto"];
                };
            };
        };
    };
    QuizzesController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizDto"];
                };
            };
        };
    };
    QuizzesController_startAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizAttemptDto"];
                };
            };
        };
    };
    QuizzesController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitQuizDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizAttemptDto"];
                };
            };
        };
    };
    QuizzesController_getQuizAttempts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizAttemptDetailDto"][];
                };
            };
        };
    };
}
