import { useEffect, useRef, useState } from "react"
import { useReports } from "@/hooks/use-reports"
import { EmptyState } from "@/components/ui/EmptyState"
import { LoadingState } from "@/components/shared/LoadingState"
import { Button } from "@/components/ui/button"
import { fetchReportHtml, openReportHtml, downloadReportHtml } from "@/lib/api"

export function ReportsPage() {
 const { reports, isLoading } = useReports()
 const [selectedId, setSelectedId] = useState<string | null>(null)
 const [previewUrl, setPreviewUrl] = useState<string | null>(null)
 const [previewLoading, setPreviewLoading] = useState(false)
 const [openLoading, setOpenLoading] = useState<string | null>(null)
 const [downloadLoading, setDownloadLoading] = useState<string | null>(null)
 const autoSelected = useRef(false)

 useEffect(() => {
  return () => {
   setPreviewUrl((current) => {
    if (current) URL.revokeObjectURL(current)
    return null
   })
  }
 }, [])

 const handleSelect = async (id: string) => {
  setSelectedId(id)
  setPreviewUrl((current) => {
   if (current) URL.revokeObjectURL(current)
   return null
  })
  setPreviewLoading(true)
  try {
   const { blob } = await fetchReportHtml(id)
   setPreviewUrl(URL.createObjectURL(blob))
  } catch {
   setPreviewUrl(null)
  } finally {
   setPreviewLoading(false)
  }
 }

 useEffect(() => {
  if (autoSelected.current) return
  if (isLoading || reports.length === 0) return
  autoSelected.current = true
  const id = reports[0].id
  const timer = setTimeout(() => {
   void handleSelect(id)
  }, 0)
  return () => clearTimeout(timer)
 }, [isLoading, reports])

 const selected = reports.find((r) => r.id === selectedId) ?? null

 const handleOpen = async (id: string) => {
  setOpenLoading(id)
  try {
   await openReportHtml(id)
  } finally {
   setOpenLoading(null)
  }
 }

 const handleDownload = async (id: string) => {
  setDownloadLoading(id)
  try {
   await downloadReportHtml(id)
  } finally {
   setDownloadLoading(null)
  }
 }

 return (
  <div className="flex-1 h-full min-h-0 p-md w-full flex flex-col">
   <h1 className="font-headline-md text-headline-md text-primary mb-sm">Reports</h1>

   {isLoading ? (
    <LoadingState className="py-xl" />
   ) : reports.length === 0 ? (
    <EmptyState icon="description" title="No reports found" description="Reports generated by the system will appear here." />
   ) : (
    <div className="flex-1 min-h-0 rounded-lg border border-border bg-surface-container-lowest overflow-hidden flex flex-col">
     <div className="flex items-center justify-between gap-2 flex-wrap border-b border-border p-md shrink-0">
      <div className="flex items-center gap-2 min-w-0">
       <span className="material-symbols-outlined text-[18px] text-on-surface-variant">description</span>
       <select
        value={selectedId ?? ""}
        onChange={(e) => handleSelect(e.target.value)}
        className="max-w-full rounded-lg border border-outline-variant bg-surface-container-low px-sm py-1.5 font-label-md text-label-md text-on-surface outline-none focus:border-primary"
        aria-label="Select report"
       >
        {reports.map((r) => (
         <option key={r.id} value={r.id}>
          Student {r.studentId.slice(0, 8)} · {new Date(r.createdAt).toLocaleDateString()}
         </option>
        ))}
       </select>
      </div>

      <div className="flex items-center gap-2">
       <Button
        type="button"
        onClick={() => selected && handleOpen(selected.id)}
        disabled={!selected || openLoading === selected.id}
        className="h-auto px-md py-sm bg-primary text-primary-foreground font-label-md text-label-md rounded-lg nudge-hover gap-1"
       >
        <span className="material-symbols-outlined text-body-lg">open_in_new</span>
        {openLoading === selected?.id ? "Opening..." : "Open"}
       </Button>
       <Button
        type="button"
        onClick={() => selected && handleDownload(selected.id)}
        disabled={!selected || downloadLoading === selected.id}
        className="h-auto px-md py-sm bg-surface-container-high text-on-surface font-label-md text-label-md rounded-lg nudge-hover gap-1"
       >
        <span className="material-symbols-outlined text-body-lg">download</span>
        {downloadLoading === selected?.id ? "Downloading..." : "Download"}
       </Button>
      </div>
     </div>

     <div className="flex-1 min-h-0">
      {previewLoading ? (
       <LoadingState className="h-full flex items-center justify-center" />
      ) : previewUrl ? (
       <iframe title="Report preview" src={previewUrl} className="w-full h-full border-0" />
      ) : (
       <div className="h-full flex items-center justify-center p-lg text-center">
        <p className="font-body-md text-body-md text-on-surface-variant">
         Preview could not be loaded. Use the buttons above.
        </p>
       </div>
      )}
     </div>
    </div>
   )}
  </div>
 )
}